.github/workflows/dartcodemetrics.yaml
example/pubspec.lock
lib/presentation/components/feed/feed_component.dart
lib/presentation/components/place/place_component.dart
lib/presentation/components/place/place_ui_model.dart
lib/presentation/presentation.dart
pubspec.lock

- dart code metrics added rules
- moved place model to this repo

- feed bugfix

---

lib/presentation/components/feed/feed_component.dart

исправлена обрезка картинки для рек ивента

Fixing UI issues

---

lib/presentation/components/feed/feed_component.dart
lib/presentation/components/shuffle/shuffle_component.dart

added error widget for photos in feed

---

lib/presentation/components/about_user/about_user_component.dart
lib/presentation/components/donation/donation_component.dart
lib/presentation/components/profile/edit_profile_component/edit_profile_default_component.dart

changes for bugfixes

---

lib/presentation/common/web_photo_video_selector.dart
lib/presentation/components/place/create_web_place_component.dart

Фиксы некоторых недочетов для CreateWebPlaceComponent'а(сначала нужен _мердж_ [SHF-442(UiKit)](https://github.com/shuffle-app/shuffle_uikit/pull/257))

SHF-442, fixes

---

lib/presentation/components/feed/feed_component.dart
lib/presentation/components/invite/invite_component.dart
lib/presentation/components/profile/edit_profile_component/edit_profile_default_component.dart
lib/presentation/components/profile/profile_component.dart

Fixes from
https://azart.atlassian.net/browse/SHF-521?atlOrigin=eyJpIjoiNTM4MzhhYjVkYTUxNDZkYmE4Nzg2NDA1MTI1Yzk4OGEiLCJwIjoiaiJ9

bugfixes from Shuffle Service

---

lib/presentation/components/invite/invite_component.dart
lib/presentation/components/invite/ui_invite_person_model.dart

Added callback to invite selected users so that app can send a request

minor changes to InviteComponent

---

lib/presentation/components/profile/profile_component.dart

[пулл в uiKit'е](https://github.com/shuffle-app/shuffle_uikit/pull/322)

feat: added howItWorks widget to profileComponent

---

example/lib/main.dart
lib/presentation/components/welcome/first_body.dart
lib/presentation/components/welcome/last_body.dart
lib/presentation/components/welcome/welcome_component.dart

fixing slow frames in welcome page

---

lib/presentation/components/about_user/about_user_component.dart
lib/presentation/components/mood/mood_component.dart

depends on PR https://github.com/shuffle-app/shuffle_uikit/pull/342

SHF 608,SHF 613

---

lib/presentation/components/messenger/chat/chat_component.dart

related to SHF-643
https://azart.atlassian.net/browse/SHF-643?atlOrigin=eyJpIjoiNWFmODNhMWQ1MTA5NDJkNDk0NzBhM2ViYmMzNTc0YmIiLCJwIjoiaiJ9

refactored chat component

---

lib/presentation/components/event/event_component.dart
lib/presentation/components/place/place_component.dart

task link
https://azart.atlassian.net/browse/SHF-656?atlOrigin=eyJpIjoiYjZjZjNkNDIxZGJkNDM5NWI2YTcyZjQzZjkzOTk1MWIiLCJwIjoiaiJ9

fixing share button

---

config.json
lib/presentation/components/about_user/about_user_component.dart
lib/presentation/components/auth/credentials_verification/personal_credentials_verification_component.dart
lib/presentation/components/donation/donation_component.dart
lib/presentation/components/feed/feed_component.dart
lib/presentation/components/messenger/all_chats_component.dart
lib/presentation/components/mood/mood_component.dart
lib/presentation/components/profile/edit_profile_component/edit_profile_default_component.dart
lib/presentation/components/profile/followings_component/followings_component.dart
lib/presentation/components/profile/notifications_component/notifications_list_component.dart
lib/presentation/components/profile/profile_component.dart
lib/presentation/components/profile/support_components/faq_component.dart
lib/presentation/components/profile/support_components/support_component.dart
lib/presentation/components/profile/uiprofile_model.dart
lib/presentation/widgets/under_development.dart

what was done
1. Прыгает плашка языка в логин пэйдж
2. Изменить Terms of Use and Service на Terms of Service
7. Орфография в social разделе -> Cloths в Clothes
8. Убрать лишний раздел поиска рождество и новый год
9. Облако с треугольником
10. Форма редактирования пользователя
11. Поиск в свойствах пользователя на экране изменить данные пользователя
12. Убрать снэкбар когда вырубили хинт система
13. New donates убрать в уведомлениях
14. Убрать моки уведомлений в See All
15. Показывать что нет контента в фолловингс
16. Убираем локейшн и воллет в настройках профиля
17. Убираем бэйджи на иконках в профиле
what needs to be done
3. Зависает экран карты - экран, где строится маршрут в деталях ивента/места
4. Не грузятся фото - проблема скорее всего с серваком, потому что вылетает ошибка что …

some changes according to design session

---

lib/presentation/common/subscription_offer_widget.dart
lib/presentation/components/feed/feed_component.dart
lib/presentation/components/place/place_component.dart
lib/presentation/components/search/results/search_result_component.dart
lib/presentation/components/search/search_component.dart
lib/presentation/components/shuffle/shuffle_component.dart

some changes for shuffle_component.dart to improve performance removed hero animation in search_component.dart and search_result_component.dart changed fingerprint animation

removed unnecessary widgets in place_component.dart

---

lib/presentation/components/about_user/about_user_component.dart

сломались иконки гендеров. тут небольшой фикс

fixing registration page icon errors

---

lib/presentation/components/event/create_web_event_component.dart
lib/presentation/components/location/location_component.dart
lib/presentation/components/place/create_web_place_component.dart

show all categories in creation forms

show initial coordinates marker

---

lib/data/base_ui_models/advertisable.dart
lib/presentation/common/place_preview.dart
lib/presentation/components/event/event_component.dart

fixing picture aspect ratio in content cards

added new ad banners

---

lib/presentation/components/profile/profile_component.dart

related to https://github.com/shuffle-app/shuffle_uikit/pull/425

Admin panel fixes

---

lib/data/base_ui_models/advertisable.dart
lib/presentation/components/feed/feed_component.dart
lib/presentation/components/search/results/search_result_component.dart

added onChanged callback in search_result_component.dart to avoid triggering searchController listener when search field gets focused
added ignore parameter in advertisable.dart
added padding in feed_component.dart

Minor bugfixes for SFK-141

---

lib/presentation/components/promotions/audience/audience_form_component.dart

fix: spacing and
